### ISSUE TITLE
Upgrade QA Wayback to PyWB 2.6.2

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-services#51] opened 2021-11-12 15:57 UTC
Following https://github.com/ukwa/ukwa-pywb/issues/71, upgrade W3ACT's Wayback and verify with @crarugal that https://github.com/ukwa/ukwa-pywb/issues/70 is resolved.

**Comment by ikreymer** [comment] 2021-11-13 02:05
Should now be 2.6.2 due to regression in 2.6.1 (now fixed).

**Comment by anjackson** [comment] 2021-12-10 12:56
This is now released on DEV, as per https://github.com/ukwa/ukwa-pywb/issues/70

**Comment by anjackson** [comment] 2021-12-15 16:31
This is done but awaiting rollout.

**Closed** 2021-12-15 16:43 UTC
Labels: bug
